name: Report Bug
description: "Report a bug that does not abruptly end a game session or prevent the start of the game."
labels:
- "Type: bug"
body:
- type: markdown
  attributes:
    value: 'Examples of this category include: item duping, item voiding, cannot craft item, behavior and description does not match.'
- type: input
  id: version
  attributes:
    label: Your Pack Version
    description: What version of the pack are you playing?
    placeholder: "Example: 1.4.2"
  validations:
    required: true
- type: dropdown
  id: instance
  attributes:
    label: Type of Instance
    description: The type of game instance you are experiencing crashes.
    options:
    - Single Player
    - Multiplayer
  validations:
    required: true
- type: textarea
  id: expectation
  attributes:
    label: Your Expectation
    description: What did you try to do, and what did you expect to happen? Attach screenshots if needed.
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: The Reality
    description: What happened instead? Attach screenshots if needed.
  validations:
    required: true
- type: textarea
  id: proposal
  attributes:
    label: Your Proposal
    description: Please describe it briefly in one or two sentences.
  validations:
    required: true
- type: checkboxes
  id: final
  attributes:
    label: Final Checklist
    description: Please mark them so we can better handle this report
    options:
      - label: "I have searched this issue tracker and there is nothing similar already."
        required: true
      - label: "I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole."
        required: false
